services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  web:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
    depends_on:
      - api

  redis:
    image: "redis:alpine"
